// Generated by CoffeeScript 1.3.3
(function() {
  var getLinks;

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    if (request.askFor !== "links") {
      return;
    }
    return sendResponse(getLinks());
  });

  getLinks = function() {
    var linkJSON, linkTag, linkTags, _i, _len;
    linkTags = document.getElementsByTagName('link');
    linkJSON = {
      'links': []
    };
    for (_i = 0, _len = linkTags.length; _i < _len; _i++) {
      linkTag = linkTags[_i];
      linkJSON.links.push({
        rel: linkTag.rel,
        href: linkTag.href,
        title: linkTag.title,
        type: linkTag.type,
        media: linkTag.media
      });
    }
    return linkJSON;
  };

}).call(this);
