// Generated by CoffeeScript 1.3.3
(function() {
  var getLinks;

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    if (request.askFor !== "links") {
      return;
    }
    return sendResponse(getLinks());
  });

  getLinks = function() {
    var linkTag, _i, _len, _ref, _results;
    _ref = document.getElementsByTagName('link');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      linkTag = _ref[_i];
      _results.push({
        rel: linkTag.rel,
        href: linkTag.href,
        title: linkTag.title,
        type: linkTag.type,
        media: linkTag.media
      });
    }
    return _results;
  };

}).call(this);
