// Generated by CoffeeScript 1.3.3
(function() {
  var LinkEnumerator;

  LinkEnumerator = (function() {

    function LinkEnumerator() {}

    LinkEnumerator.addLink = function(root, linkTag) {
      var a, li;
      li = root.appendChild(document.createElement('li'));
      a = li.appendChild(document.createElement('a'));
      a.href = linkTag.href;
      return a.innerText = linkTag.href;
    };

    LinkEnumerator.addListOfLinks = function() {
      return chrome.tabs.getSelected(null, function(tab) {
        return chrome.tabs.sendMessage(tab.id, {
          askFor: 'links'
        }, function(linkTags) {
          var li, linkTag, root, _i, _len, _results;
          root = document.getElementById('links');
          if (linkTags == null) {
            li = root.appendChild(document.createElement('li'));
            li.innerText = 'No link tags found.';
            return;
          }
          _results = [];
          for (_i = 0, _len = linkTags.length; _i < _len; _i++) {
            linkTag = linkTags[_i];
            _results.push(LinkEnumerator.addLink(root, linkTag));
          }
          return _results;
        });
      });
    };

    return LinkEnumerator;

  })();

  document.addEventListener('DOMContentLoaded', function() {
    return LinkEnumerator.addListOfLinks();
  });

}).call(this);
